### ISSUE TITLE
Add test files and test that built graph matches

### ISSUE THREAD

**Issue by s3n-w6i** [precice-forschungsprojekt/config-graph#11]
**Description**

This could be a possible folder structure for tests:

```
test
|--- example-configs
       |--- config-a
       |     |--- precice-config.xml
       |     |--- test.py
       |--- config-b
       |     |--- precice-config.xml
       |     |--- test.py
       |--- ...

```

**Subtasks**
- [x] Add a folder of possible configs (see https://github.com/precice/precice/tree/develop/tests)
- [x] Define what a graph for this config must look like
- [x] For each file, add a `test.py` that does to following:
  - [x] Execute `get_graph` to return the graph that our library builds
  - [x] Compare the result to the expected graph
- [x] ~~Add a python script in the `test` folder that executes all individual tests~~ (not needed because we use pytest)

**Dependencies**
This task depends on #2 to be finished.

**Comment by s3n-w6i** [comment]
pytest
